### ISSUE TITLE
Same output on different input

### ISSUE THREAD

**Issue by dfcreative** [blakeembrey/param-case#2]
Hi @blakeembrey!
I am using param-case in [control-panel](https://github.com/freeman-lab/control-panel) and found out that `range slider (log)` and `range slider (-log)` inputs after formatting give the same output:
```js
var format = require('param-case')
assert.equal(format('range slider (log)'), format('range slider (-log)'));
```
That is not very good for the package’s purposes.
Is it considered a bug or a feature?

Thanks!

**Comment by blakeembrey** [comment]
This is expected (so feature), no punctuation is kept in tact. Both these would end up equalling `range-slider-log`. What are you trying to do?

**Comment by dfcreative** [comment]
I have labels for fields, which are in human-readable form, like in the example. They are then converted to ids for the input tags, so that a label uniquely identifies an input. In case if label text differs from other label only by the minus sign, it points to the wrong input.

**Comment by dfcreative** [comment]
I used just ´label.replace(/\s/g, '-')´ before, it worked out in that case.

**Comment by blakeembrey** [comment]
Gotcha. Yeah, might be worth using a different approach for that that doesn't remove characters. You can easily generate unique IDs based on a string by using a consistent encoding scheme - even something like `encodeURIComponent(str).replace('%', '_')` might work? I know I've done that for generate filenames of cache keys before. Or `str.replace(/[^\w-]/g, val => val.charCodeAt(0))`. Depends on what you'd like to do.

**Comment by blakeembrey** [comment]
I'd go the approach of making a whitelist of characters you know work, then replace the rest with something consistent that can't (reasonably) conflict when encoded.

**Comment by dfcreative** [comment]
Yeh, I see. It looks verbose as I use it like in 7 different components, so I hoped there might be a module solution. Ok, I guess that is not a big deal.

**Comment by dfcreative** [comment]
I also consider that a feature, hehe)

**Comment by blakeembrey** [comment]
Fair enough. The problem is most things won't generate you a unique string based on input - most will just sanitize. This is the same for slugging, etc. In this case, you just need a simple solution that generates a unique string based on a whitelist of characters. You can even fallback to hashes or just incremented IDs (if it's not important how it looks). If you take a look at markdown renderers, they even end up with conflicts on the header IDs (E.g. in GitHub) because they'd just slugify the string and end up with something like this module.

**Comment by dfcreative** [comment]
I see, but that's ok for this case. Wrong focus in rare cases is not a big deal, considering that there was no focus at all. It is not a database hehe)
