### ISSUE TITLE
Problem with multiple capital letters followed by lowercase

### ISSUE THREAD

**Issue by codysherman** [blakeembrey/param-case#6]
@kangax is using your neat little repo on https://github.com/kangax/html-minifier to convert the flags in the command line. (See [the file cli.js](https://github.com/kangax/html-minifier/blob/471f9f28173841f2d4b383d5b9dd963a51b21b32/cli.js) lines 119 & 142 for reference). Unfortunately one of the commands has a little bit of a bug. "minifyURLs" becomes "--minify-ur-ls" as the lowercase letter triggers the previous letter to be seen as a new word. In this case, the ideal solution would be that it becomes "minify-urls".

Logically I think you could do something where if groups of lowercase letters are just part of the previous group, rather than just the last capital letter.

Examples:

minifyURLs -> minify-urls
minifyURLssss -> minify-urlssss
minifyURLsFFoo -> minify-urls-ffoo

**Comment by blakeembrey** [comment]
I know it sounds nice to say “logically just do this”, but it’s unfortunately not always that easy. If it were logical, it would have been implemented that way.

I’d need to verify and pull back examples, but I think it was implemented this way in the previous major version. Off the top of my head, it would fail on any of your examples that don’t happen to end an upper cased word in lowercase, which I believe is pretty uncommon. For example `XMLHttpRequest`.

**Comment by blakeembrey** [comment]
We can put the logic behind a flag though, I think it’s actually a matter of skipping some logic so it shouldn’t be difficult.

**Comment by codysherman** [comment]
My apologies! When I said the logically part, I by no means meant that the answer would be easy or quick. I was more so just trying to explain what I personally thought would be only the basis of a potential fix, and that obviously more thought would have to go into it. If you do discover a way to solve it quick, then amazing, otherwise, was just trying to point in a direction that _could maybe_ lead to the solution!

**Comment by blakeembrey** [comment]
Documented how it can be customized in https://github.com/blakeembrey/change-case/tree/master/packages/no-case#options.
